---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.2.20

verifier:
  name: inspec

platforms:
  - name: centos-7.3
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[kibana5-test]
      - recipe[kibana5-test::wait_kibana_start]

  - name: nginx
    run_list:
      - recipe[kibana5-test]
      - recipe[kibana5-test::nginx]
      - recipe[kibana5-test::wait_kibana_start]
